server:
  port: 8099
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: h_route
  cloud:
    gateway:
      routes:
      - id: h_route
        uri: http://demo.hperson.com/get
        predicates:
        - Path=/api/{segment}
    profiles: h_route
  
        
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 106.12.16.45
  client:
    serviceUrl:
      defaultZone: http://eureka.hperson.com/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
